version: "3.4"
 
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
    volumes:
      - ./postgres:/var/lib/postgresql/data
 
